#!/usr/bin/env python3
"""
Render resources/configuration.prop, resources/TREDHibernate.cfg.xml, and
resources/funcIntHibernate.cfg.xml from templates/*.tmpl + build.params.

Usage:
    python3 scripts/render_config.py [--dry-run]

build.params is the single source of truth for values that change from one FI
network build to the next; don't hand-edit the generated files.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PARAMS_FILE = os.path.join(ROOT, "build.params")
TEMPLATES_DIR = os.path.join(ROOT, "templates")

REQUIRED_KEYS = [
    "YEAR", "DATE", "RF_DATE", "FEATURE_FILE_DATE", "REACTOME_RELEASE", "PREV_REACTOME_RELEASE",
    "GK_CENTRAL_DB_NAME",
    "DB_USER", "DB_PWD", "MYSQLDUMP", "RESULT_ROOT", "DATASET_ROOT",
    "UNIPROT_RELEASE", "PFAM_RELEASE", "PANTHER_VERSION", "PANTHER_ORTHOLOG_VERSION",
    "ENSEMBL_RELEASE", "BIOGRID_VERSION", "STRING_VERSION", "IDG_FI_NETWORK_ML_DIR",
    "PRE_GENE_TO_TOPIC_FILE", "WEBAPP_DIR",
]
# Allowed to be blank until the human review step (see build.params comment).
OPTIONAL_KEYS = ["CUT_OFF_VALUE"]

TARGETS = [
    ("configuration.prop.tmpl", os.path.join(ROOT, "resources", "configuration.prop")),
    ("TREDHibernate.cfg.xml.tmpl", os.path.join(ROOT, "resources", "TREDHibernate.cfg.xml")),
    ("funcIntHibernate.cfg.xml.tmpl", os.path.join(ROOT, "resources", "funcIntHibernate.cfg.xml")),
]


def load_params(path):
    params = {}
    with open(path) as f:
        for raw_line in f:
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            key, _, value = line.partition("=")
            params[key.strip()] = value.strip()
    return params


def check_required(params):
    missing = [k for k in REQUIRED_KEYS if not params.get(k)]
    if missing:
        sys.exit("build.params is missing required value(s): " + ", ".join(missing))
    for k in OPTIONAL_KEYS:
        params.setdefault(k, "")


def derive(params):
    d = dict(params)
    d["PANTHER_VERSION_UNDERSCORE"] = d["PANTHER_VERSION"].replace(".", "_")
    # PRE_GENE_TO_TOPIC_FILE may reference ${RESULT_ROOT} for convenience in build.params;
    # resolve it here since RESULT_ROOT itself is not a key in the rendered configuration.prop
    # (only RESULT_DIR is), so it can't be resolved by FIConfiguration's runtime substitution.
    d["PRE_GENE_TO_TOPIC_FILE"] = d["PRE_GENE_TO_TOPIC_FILE"].replace("${RESULT_ROOT}", d["RESULT_ROOT"])
    cutoff = d.get("CUT_OFF_VALUE", "").strip()
    if cutoff:
        d["CUT_OFF_VALUE_LINE"] = "CUT_OFF_VALUE=%sd" % cutoff
    else:
        d["CUT_OFF_VALUE_LINE"] = "#CUT_OFF_VALUE= # not set yet - see build.params"
    return d


def render(template_text, values):
    def repl(m):
        key = m.group(1)
        if key not in values:
            sys.exit("Template references unknown placeholder {{%s}}" % key)
        return values[key]
    return re.sub(r"\{\{(\w+)\}\}", repl, template_text)


def write_if_changed(path, content, dry_run):
    old = None
    if os.path.exists(path):
        with open(path) as f:
            old = f.read()
    if old == content:
        print("unchanged: %s" % os.path.relpath(path, ROOT))
        return
    if dry_run:
        print("would write: %s" % os.path.relpath(path, ROOT))
        return
    with open(path, "w") as f:
        f.write(content)
    print("wrote: %s" % os.path.relpath(path, ROOT))


def write_build_env(values, dry_run):
    keys = [
        "YEAR", "DATE", "RF_DATE", "FEATURE_FILE_DATE", "REACTOME_RELEASE", "PREV_REACTOME_RELEASE",
        "DB_USER", "DB_PWD", "MYSQLDUMP", "RESULT_ROOT", "DATASET_ROOT",
        "UNIPROT_RELEASE", "PFAM_RELEASE", "PANTHER_VERSION", "PANTHER_ORTHOLOG_VERSION",
        "ENSEMBL_RELEASE", "BIOGRID_VERSION", "STRING_VERSION", "IDG_FI_NETWORK_ML_DIR",
        "CUT_OFF_VALUE",
    ]
    lines = ["# GENERATED by scripts/render_config.py - do not hand-edit."]
    # Base scalar values first - derived exports below reference these via ${...},
    # and bash expands that at export time, so order matters.
    for k in keys:
        lines.append('export %s="%s"' % (k, values[k]))
    lines.append("export RESULT_DIR=\"%s/${YEAR}\"" % values["RESULT_ROOT"])
    lines.append("export DATA_SET_DIR=\"%s/FI_${YEAR}\"" % values["DATASET_ROOT"])
    lines.append('export REACTOME_SOURCE_DB_NAME="reactome_${REACTOME_RELEASE}_plus_i"')
    lines.append('export MOUSE_SOURCE_DB_NAME="reactome_${REACTOME_RELEASE}_plus_i"')
    lines.append('export PREV_REACTOME_SOURCE_DB_NAME="reactome_${PREV_REACTOME_RELEASE}_plus_i"')
    lines.append('export REACTOME_GK_CENTRAL_DB_NAME="%s"' % values["GK_CENTRAL_DB_NAME"])
    lines.append('export FI_DB_NAME="FI_${YEAR}"')
    lines.append('export UNIPROT_DIR="${DATA_SET_DIR}/UniProt/${UNIPROT_RELEASE}"')
    lines.append('export PFAM_DIR_NAME="${DATA_SET_DIR}/Pfam/${PFAM_RELEASE}"')
    lines.append('export PANTHER_DIR="${DATA_SET_DIR}/Panther/Version${PANTHER_VERSION}"')
    lines.append('export PANTHER_ORTHOLOG_DIR="${DATA_SET_DIR}/Panther/ortholog_${PANTHER_ORTHOLOG_VERSION}"')
    lines.append('export ENSEMBL_DIR="${DATA_SET_DIR}/Ensembl/release_${ENSEMBL_RELEASE}"')
    content = "\n".join(lines) + "\n"
    path = os.path.join(ROOT, ".build_env.sh")
    write_if_changed(path, content, dry_run)


def main():
    dry_run = "--dry-run" in sys.argv[1:]
    params = load_params(PARAMS_FILE)
    check_required(params)
    values = derive(params)

    for template_name, target_path in TARGETS:
        template_path = os.path.join(TEMPLATES_DIR, template_name)
        with open(template_path) as f:
            template_text = f.read()
        content = render(template_text, values)
        write_if_changed(target_path, content, dry_run)

    write_build_env(values, dry_run)

    # RESULT_DIR/DATA_SET_DIR are the build's own output/input trees - nothing else
    # creates them (fetch_datasets.sh only creates specific dataset subdirectories),
    # so the pipeline fails on FileNotFoundException the first time anything tries
    # to write into RESULT_DIR unless it's created up front.
    result_dir = "%s/%s" % (values["RESULT_ROOT"], values["YEAR"])
    data_set_dir = "%s/FI_%s" % (values["DATASET_ROOT"], values["YEAR"])
    for d in (result_dir, data_set_dir):
        if dry_run:
            print("would ensure directory exists: %s" % d)
        else:
            os.makedirs(d, exist_ok=True)

    if dry_run:
        print("\nDry run - no files were written.")


if __name__ == "__main__":
    main()
